### ISSUE TITLE
Workspaces shuffled on wake after sleep

### ISSUE THREAD

**Issue by thundron** [glzr-io/glazewm#600]
Similar to https://github.com/glzr-io/glazewm/issues/283, it seems like workspaces are shuffled between monitors upon wake after monitors shut off in a multi monitor setup

I set the proper bindings in the configuration file (even though, as per linked issue, the primary monitor is seen as secondary)

**Comment by lars-berger** [comment]
Crashes and inconsistencies on display setting changes, system standby, and monitor disconnections should now be fixed in v3 🎉 [Latest release](https://github.com/glzr-io/glazewm/releases)

**Comment by thundron** [comment]
Amazing work, I'm gonna give it a try as soon as I get back to my desktop next week!

**Comment by vlad420** [comment]
Same for me. For Zebar if you right click on the bar and hit refresh (for each monitor) it works again. But is annoying.

> @lars-berger Still getting bugs in Zebar — no visual indication for selected workspace after laptop goes to sleep. It connected to a second display.

**Comment by thundron** [comment]
Can confirm the issue is still happening; also at startup, on 2 monitors, I only see Zebar on one of them, but that's a separate issue
